import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import {
  WS_CLOSE_SUPERSEDED,
  WS_CLOSE_UNAUTHORIZED,
  WS_CLOSE_BAD_REGISTER,
} from '@browserhandle/protocol';
import type { CallResponse, HandleInfo, HealthInfo } from '@browserhandle/protocol';
import { createRelay } from '../server.js';
import type { Relay } from '../server.js';
import type { AuthConfig } from '../auth.js';
import { connectFakeExtension, FakeExtension } from './fake-extension.js';

/** Start a relay on an ephemeral loopback port for a test. */
async function startRelay(auth?: AuthConfig): Promise<{ relay: Relay; port: number; base: string }> {
  const relay = createRelay({ host: '127.0.0.1', port: 0, auth });
  const { port } = await relay.listen();
  return { relay, port, base: `http://127.0.0.1:${port}` };
}

interface Harness {
  relay: Relay;
  port: number;
  base: string;
  extensions: FakeExtension[];
}

let h: Harness;

beforeEach(async () => {
  const { relay, port, base } = await startRelay();
  h = { relay, port, base, extensions: [] };
});

afterEach(async () => {
  for (const ext of h.extensions) ext.close();
  await h.relay.close();
});

function track(ext: FakeExtension): FakeExtension {
  h.extensions.push(ext);
  return ext;
}

async function listHandles(base: string, token?: string): Promise<{ status: number; body: HandleInfo[] }> {
  const res = await fetch(`${base}/v1/handles`, {
    headers: token ? { authorization: `Bearer ${token}` } : {},
  });
  return {
    status: res.status,
    body: res.status === 200 ? ((await res.json()) as HandleInfo[]) : [],
  };
}

async function call(
  base: string,
  handleId: string,
  body: unknown,
  token?: string
): Promise<{ status: number; body: CallResponse }> {
  const res = await fetch(`${base}/v1/handles/${encodeURIComponent(handleId)}/call`, {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      ...(token ? { authorization: `Bearer ${token}` } : {}),
    },
    body: JSON.stringify(body),
  });
  return { status: res.status, body: (await res.json()) as CallResponse };
}

describe('health endpoint', () => {
  it('reports liveness with no auth and no handle ids', async () => {
    const res = await fetch(`${h.base}/healthz`);
    expect(res.status).toBe(200);
    const body = (await res.json()) as HealthInfo;
    expect(body.ok).toBe(true);
    expect(body.handles).toEqual({ connected: 0, total: 0 });
    expect(JSON.stringify(body)).not.toContain('handleId');
  });
});

describe('registration and listing', () => {
  it('registers a handle and lists it as connected', async () => {
    track(await connectFakeExtension(h.port, { handleId: 'handle-a', name: 'Laptop' }));
    const { status, body } = await listHandles(h.base);
    expect(status).toBe(200);
    expect(body).toHaveLength(1);
    expect(body[0]).toMatchObject({ handleId: 'handle-a', name: 'Laptop', connected: true });
  });

  it('rejects a connection that never registers, with a deadline close', async () => {
    // We cannot wait the full 5s deadline here; instead send junk as the
    // first message, which is an immediate bad-register close.
    const ext = track(new FakeExtension(h.port, { handleId: 'x', autoRegister: false }));
    await new Promise((r) => ext.ws.on('open', r));
    ext.sendRaw({ not: 'a register message' });
    const { code } = await ext.closed;
    expect(code).toBe(WS_CLOSE_BAD_REGISTER);
  });

  it('rejects a protocol-version mismatch', async () => {
    const ext = track(new FakeExtension(h.port, { handleId: 'x', protocolVersion: 99 }));
    const { code } = await ext.closed;
    expect(code).toBe(WS_CLOSE_BAD_REGISTER);
    expect(ext.relayErrors[0]?.code).toBe('PROTOCOL_MISMATCH');
  });
});

describe('call routing', () => {
  it('routes a call to the extension and returns its result', async () => {
    const ext = track(
      await connectFakeExtension(h.port, {
        handleId: 'h1',
        respond: (req) => ({ method: req.method, ok: true }),
      })
    );
    const { status, body } = await call(h.base, 'h1', { method: 'ping' });
    expect(status).toBe(200);
    expect(body).toEqual({ ok: true, result: { method: 'ping', ok: true } });
    expect(ext.requests.map((r) => r.method)).toContain('ping');
  });

  it('assigns a fresh envelope id (ignores agent-controlled ids)', async () => {
    const ext = track(await connectFakeExtension(h.port, { handleId: 'h1' }));
    await call(h.base, 'h1', { method: 'ping' });
    // The id the extension saw is a UUID generated by the relay, not anything
    // the agent supplied (the agent has no id field at all).
    expect(ext.requests[0].id).toMatch(/[0-9a-f-]{8,}/);
  });

  it('surfaces a bridge error as 200 ok:false (not a relay failure)', async () => {
    track(
      await connectFakeExtension(h.port, {
        handleId: 'h1',
        respond: () => {
          throw new Error('stale ref');
        },
      })
    );
    const { status, body } = await call(h.base, 'h1', { method: 'click', payload: {} });
    expect(status).toBe(200);
    expect(body.ok).toBe(false);
    if (!body.ok) expect(body.error.code).toBe('HANDLER_ERROR');
  });

  it('returns a 413 (not a dropped connection) when the body exceeds the limit', async () => {
    // 33 MB > MAX_BODY_BYTES (32 MB). The relay must still deliver the 413
    // response rather than destroying the socket (ECONNRESET).
    const oversized = 'x'.repeat(33 * 1024 * 1024);
    const res = await fetch(`${h.base}/v1/handles/h1/call`, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: oversized,
    });
    expect(res.status).toBe(413);
    const body = (await res.json()) as CallResponse;
    expect(body.ok).toBe(false);
    if (!body.ok) expect(body.error.code).toBe('INVALID_REQUEST');
  });

  it('returns 404 HANDLE_NOT_FOUND for an unknown handle', async () => {
    const { status, body } = await call(h.base, 'ghost', { method: 'ping' });
    expect(status).toBe(404);
    expect(body.ok).toBe(false);
    if (!body.ok) expect(body.error.code).toBe('HANDLE_NOT_FOUND');
  });

  it('rejects an unknown method with 400 INVALID_REQUEST', async () => {
    track(await connectFakeExtension(h.port, { handleId: 'h1' }));
    const { status, body } = await call(h.base, 'h1', { method: 'launchMissiles' });
    expect(status).toBe(400);
    if (!body.ok) expect(body.error.code).toBe('INVALID_REQUEST');
  });
});

describe('concurrent correlation', () => {
  it('correlates interleaved calls across two handles', async () => {
    // Each extension echoes the unique marker it was given in the payload,
    // after a per-request delay, so responses come back out of order.
    const make = (id: string) =>
      connectFakeExtension(h.port, {
        handleId: id,
        respond: async (req) => {
          const payload = req.payload as { marker: number; delay: number };
          await new Promise((r) => setTimeout(r, payload.delay));
          return { handle: id, marker: payload.marker };
        },
      });

    track(await make('A'));
    track(await make('B'));

    const calls: Promise<{ handle: string; marker: number }>[] = [];
    for (let i = 0; i < 10; i++) {
      const handle = i % 2 === 0 ? 'A' : 'B';
      const delay = (10 - i) * 5; // later calls finish sooner -> reordering
      calls.push(
        call(h.base, handle, { method: 'evaluate', payload: { marker: i, delay } }).then((r) => {
          if (!r.body.ok) throw new Error('unexpected failure');
          return r.body.result as { handle: string; marker: number };
        })
      );
    }

    const results = await Promise.all(calls);
    results.forEach((result, i) => {
      expect(result.marker).toBe(i);
      expect(result.handle).toBe(i % 2 === 0 ? 'A' : 'B');
    });
  });
});

describe('supersede', () => {
  it('closes the old socket with 4409 when the same handle reconnects', async () => {
    const first = track(await connectFakeExtension(h.port, { handleId: 'dup' }));
    const second = track(await connectFakeExtension(h.port, { handleId: 'dup' }));

    const { code } = await first.closed;
    expect(code).toBe(WS_CLOSE_SUPERSEDED);

    // The new socket serves calls.
    const { body } = await call(h.base, 'dup', { method: 'ping' });
    expect(body.ok).toBe(true);
    expect(second.requests).toHaveLength(1);

    // Still exactly one handle in the registry.
    const { body: handles } = await listHandles(h.base);
    expect(handles.filter((x) => x.handleId === 'dup')).toHaveLength(1);
  });
});

describe('timeout and disconnect', () => {
  it('returns 504 RELAY_TIMEOUT when the extension never answers', async () => {
    track(await connectFakeExtension(h.port, { handleId: 'h1', mute: true }));
    const { status, body } = await call(h.base, 'h1', { method: 'ping', timeoutMs: 150 });
    expect(status).toBe(504);
    if (!body.ok) expect(body.error.code).toBe('RELAY_TIMEOUT');
  });

  it('returns 503 HANDLE_DISCONNECTED when the extension drops mid-call', async () => {
    const ext = track(
      await connectFakeExtension(h.port, {
        handleId: 'h1',
        // Receive the request, then disconnect without answering.
        respond: () => new Promise(() => {}),
      })
    );
    const pending = call(h.base, 'h1', { method: 'navigate', payload: { url: 'https://x.test' } });
    // Wait until the relay has dispatched the request to the extension.
    await new Promise((r) => setTimeout(r, 50));
    ext.terminate();
    const { status, body } = await pending;
    expect(status).toBe(503);
    if (!body.ok) expect(body.error.code).toBe('HANDLE_DISCONNECTED');
  });

  it('keeps a disconnected handle as a tombstone in the listing', async () => {
    const ext = track(await connectFakeExtension(h.port, { handleId: 'h1', name: 'Gone' }));
    ext.close();
    await ext.closed;
    await new Promise((r) => setTimeout(r, 50));
    const { body } = await listHandles(h.base);
    const entry = body.find((x) => x.handleId === 'h1');
    expect(entry).toBeDefined();
    expect(entry?.connected).toBe(false);
  });

  it('returns 503 for a call to a disconnected (tombstoned) handle', async () => {
    const ext = track(await connectFakeExtension(h.port, { handleId: 'h1' }));
    ext.close();
    await ext.closed;
    await new Promise((r) => setTimeout(r, 50));
    const { status, body } = await call(h.base, 'h1', { method: 'ping' });
    expect(status).toBe(503);
    if (!body.ok) expect(body.error.code).toBe('HANDLE_DISCONNECTED');
  });
});
